---
sudo: true
language: ruby
bundler_args: --without development system_tests
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.8
    env: PUPPET_GEM_VERSION="~> 3.0"
notifications:
  email: false
